export const playlistData = [
  {
    decade: '80s',
    sidewaysText: 'NINETEEN EIGHTIES',
    artists: [
      'AC/DC',
      'Aerosmith',
      'Beastie Boys',
      'Cheap Trick',
      'Earth, Wind, & Fire',
      'Eddie Money',
      'George Michael',
      'Huey Lewis and the News',
      'Jackson Browne',
      'Joan Jett',
      'Michael Jackson',
      'Poison',
      'Prince',
      'Queen',
      'Rick Springfield',
      'Rod Stewart',
      'Tears For Fears',
      'The Outfield',
      'The Proclaimers',
      'Tom Petty',
      'Van Halen',
      'Violent Femmes',
    ],
  },
  {
    decade: '90s',
    sidewaysText: 'NINETEEN NINETIES',
    artists: [
      'Backstreet Boys',
      'Blackstreet',
      'Blink 182',
      'David Lee Murphy',
      'Eminem',
      'Garth Brooks',
      'Gin Blossoms',
      'Ginuwine',
      'Goo Goo Dolls',
      'Green Day',
      'John Michael Montgomery',
      'Lit',
      'Montell Jordan',
      'Salt-N-Pepa',
      'Shania Twain',
      'Smash Mouth',
      'Spice Girls',
      'Sublime',
      'Third Eye Blind',
      'Tupac',
      'Warren G',
    ],
  },
  {
    decade: '00s',
    sidewaysText: 'TWO THOUSANDS',
    artists: [
      'Bruno Mars',
      'Cee Lo Green',
      'Chainsmokers',
      'Daft Punk',
      'DNCE',
      'Fitz and the Tantrums',
      'Flo Rida',
      'Jimmy Eat World',
      'Justin Timberlake',
      'Keith Urban',
      'Lady Gaga',
      'Maroon 5',
      'Miley Cyrus',
      'Sam Hunt',
      'Shaggy',
      'Taio Cruz',
      'The Killers',
      'The Weeknd',
      'Twenty One Pilots',
      'Walk the Moon',
      'Weezer',
      'Zac Brown Band',
    ],
  },
];
