export const playlistData = [
    {
      decade: "≤ 1980s",
      artists: [
        "AC/DC",
        "Aerosmith",
        "Beastie Boys",
        "Cheap Trick",
        "Cutting Crew",
        "Earth, Wind, & Fire",
        "Eddie Money",
        "George Michael",
        "Huey Lewis and the News",
        "Jackson Browne",
        "Joan Jett",
        "Michael Jackson",
        "Prince",
        "Queen",
        "Rick Springfield",
        "Rod Stewart",
        "Tears For Fears",
        "The Outfield",
        "The Proclaimers",
        "Tom Petty",
        "Violent Fems",
      ],
    },
    {
      decade: "= 1990s",
      artists: [
        "Backstreet Boys",
        "Blackstreet",
        "David Lee Murphy",
        "Garth Brooks",
        "Ginuwine",
        "Goo Goo Dolls",
        "Green Day",
        "John Michael Montgomery",
        "Lit",
        "Montell Jordan",
        "Salt-N-Pepa",
        "Shania Twain",
        "Spice Girls",
        "Sublime",
        "Warren G",
      ],
    },
    {
      decade: "≥ 2000s",
      artists: [
        "Bruno Mars",
        "Cee Lo Green",
        "Chainsmokers",
        "Daft Punk",
        "DNCE",
        "Jimmy Eat World",
        "Justin Timberlake",
        "The Weeknd",
        "Keith Urban",
        "Lady Gaga",
        "Maroon 5",
        "Sam Hunt",
        "Shaggy",
        "Taio Cruz",
        "The Killers",
        "The Weekend",
        "Tupac",
        "Twenty One Pilots",
        "Walk the Moon",
        "Weezer",
        "Zac Brown Band",
      ],
    },
  ];
  